import responseCode from "./responseCode.gen";

/** 
 * response status default message.
 * if set value as response code, response handler will set status, code & message.
 **/
export const responseStatusToCode = new Map<number, string>();
// responseStatusToCode.set(100, "Continue");
// responseStatusToCode.set(101, "Switching Protocols");
// responseStatusToCode.set(102, "Processing");
// responseStatusToCode.set(103, "Early Hints");
responseStatusToCode.set(200, responseCode.success);
responseStatusToCode.set(201, responseCode.success);
responseStatusToCode.set(202, responseCode.success);
// responseStatusToCode.set(203, "Non-Authoritative Information");
// responseStatusToCode.set(204, "No Content");
// responseStatusToCode.set(205, "Reset Content");
// responseStatusToCode.set(206, "Partial Content");
// responseStatusToCode.set(207, "Multi-Status");
// responseStatusToCode.set(208, "Already Reported");
// responseStatusToCode.set(226, "IM Used");
// responseStatusToCode.set(300, "Multiple Choices");
// responseStatusToCode.set(301, "Moved Permanently");
// responseStatusToCode.set(302, "Found");
// responseStatusToCode.set(303, "See Other");
// responseStatusToCode.set(304, "Not Modified");
// responseStatusToCode.set(307, "Temporary Redirect");
// responseStatusToCode.set(308, "Permanent Redirect");
responseStatusToCode.set(400, responseCode.err_payload);
// responseStatusToCode.set(401, responseCode.err_perm);
// responseStatusToCode.set(402, "Payment Required");
// responseStatusToCode.set(403, "Forbidden");
// responseStatusToCode.set(404, "Not Found");
// responseStatusToCode.set(405, "Method Not Allowed");
// responseStatusToCode.set(406, "Not Acceptable");
// responseStatusToCode.set(407, "Proxy Authentication Required");
// responseStatusToCode.set(408, "Request Timeout");
// responseStatusToCode.set(409, "Conflict");
// responseStatusToCode.set(410, "Gone");
// responseStatusToCode.set(411, "Length Required");
// responseStatusToCode.set(412, "Precondition Failed");
// responseStatusToCode.set(413, "Content Too Large");
// responseStatusToCode.set(414, "URI Too Long");
// responseStatusToCode.set(415, "Unsupported Media Type");
// responseStatusToCode.set(416, "Range Not Satisfiable");
// responseStatusToCode.set(417, "Expectation Failed");
// responseStatusToCode.set(418, "I'm a teapot");
// responseStatusToCode.set(421, "Misdirected Request");
// responseStatusToCode.set(422, "Unprocessable Content");
// responseStatusToCode.set(423, "Locked");
// responseStatusToCode.set(424, "Failed Dependency");
// responseStatusToCode.set(425, "Too Early");
// responseStatusToCode.set(426, "Upgrade Required");
// responseStatusToCode.set(428, "Precondition Required");
// responseStatusToCode.set(429, "Too Many Requests");
// responseStatusToCode.set(431, "Request Header Fields Too Large");
// responseStatusToCode.set(451, "Unavailable For Legal Reasons");
// responseStatusToCode.set(500, "Internal Server Error");
// responseStatusToCode.set(501, "Not Implemented");
// responseStatusToCode.set(502, "Bad Gateway");
// responseStatusToCode.set(503, "Service Unavailable");
// responseStatusToCode.set(504, "Gateway Timeout");
// responseStatusToCode.set(505, "HTTP Version Not Supported");
// responseStatusToCode.set(506, "Variant Also Negotiates");
// responseStatusToCode.set(507, "Insufficient Storage");
// responseStatusToCode.set(508, "Loop Detected");
// responseStatusToCode.set(510, "Not Extended");
// responseStatusToCode.set(511, "Network Authentication Required");

export default responseStatusToCode;