/**
 * Generated by veryExpress@0.6.3-alpha 
 * https://github.com/Justin26l/VeryExpress
 */

import { ResponseCode } from "./../../_utils/response.gen";

export interface VexResponse<T = unknown>{
    ret_code?: ResponseCode;
    ret_msg?: string | null;
    elapse?: number;
    result?: T;
}
