/**
 * Generated by veryExpress@0.6.3-alpha 
 * https://github.com/Justin26l/VeryExpress
 */

import { ResponseCode } from "./../../_utils/response.gen";

export interface VexResponse<T = unknown>{
    code?: ResponseCode;
    message?: string | null;
    result?: T;
}
