import utils from "../../utils";
import log from "../../utils/logger";
import * as types from "../../types/types";

interface SqlIndex {
    tableName: string;
    columnName: string;
}

function collectSqlIndexes(schemas: types.jsonSchema[]): SqlIndex[] {
    const indexes: SqlIndex[] = [];
    for (const schema of schemas) {
        const documentName = schema["x-documentConfig"].documentName;
        const tableName = documentName.toLowerCase();
        const props = schema.properties || {};
        for (const [key, val] of Object.entries(props)) {
            const p = val as types.jsonSchemaPropsItem;
            if (p.type === "array") {
                indexes.push({ tableName, columnName: key });
            }
        }
    }
    return indexes;
}

function sqlMigrationsTemplate(indexes: SqlIndex[]): string {
    const statements = indexes.map(({ tableName, columnName }) => {
        const indexName = `idx_${tableName}_${columnName}_gin`;
        return `    "CREATE INDEX IF NOT EXISTS ${indexName} ON \\"${tableName}\\" USING GIN (\\"${columnName}\\")"`;
    });

    return `/**
 * Generated by veryExpress 
 * Time @ ${new Date().toISOString()}
 * SQL migrations — run on every app start (idempotent via IF NOT EXISTS)
 */

export const sqlMigrations: string[] = [
${statements.join(",\n")}
];
`;
}

export async function compile(options: {
    schemas: types.jsonSchema[];
    outDir: string;
}): Promise<void> {
    log.process("SQL Migrations");
    const indexes = collectSqlIndexes(options.schemas);
    const outPath = `${options.outDir}/sqlMigration.gen.ts`;
    utils.common.writeFile("SQL Migrations", outPath, sqlMigrationsTemplate(indexes));
}

export default { compile };
