import * as types from "../types/types";
import pkg from "../../package.json";
import log from "./logger";

export function getDefaultHeaderComment(version?:string): string {
    return `/**
 * Generated by veryExpress@${version} 
 * https://github.com/Justin26l/VeryExpress
 */
`;
}

export function getStaticHeaderComment(): string {
    return `/**
 * Generated by veryExpress 
 * https://github.com/Justin26l/VeryExpress
 */
`;
}

export function getSimpleHeaderComment(): string {
    return `// Generated by veryExpress@${pkg.version}`;
}

export function getSimpleStaticHeaderComment(): string {
    return "// Generated by veryExpress";
}

export function OAuthProviders(compilerOptions: types.compilerOptions): string[] {
    return Object.keys(compilerOptions.auth.oauthProviders!).filter((key) => {
        return compilerOptions.auth.oauthProviders![key] === true;
    });
}

/**
 * Is any sign-in path configured?
 *
 * All three count. `externalIdentity` in particular is easy to miss: a broker-only app
 * (`localAuth: false`, no passport provider) is not auth-less, and treating it as such would drop the
 * whole `AuthController` — including the `/auth/external` endpoint it exists to serve.
 *
 * Reads the RAW flag rather than `isExternalIdentityEnabled()`, which calls this function; using the
 * gated helper here would recurse.
 */
export function isAuthEnabled(compilerOptions: types.compilerOptions): boolean {
    return compilerOptions.auth.localAuth
        || OAuthProviders(compilerOptions).length > 0
        || (compilerOptions.auth.externalIdentity?.enabled ?? false);
}

/**
 * Single gate for external identity: the `/auth/external` endpoint, the verifier service and the
 * login-page wiring.
 *
 * Opt-in (`?? false`), unlike account deletion: it is the one feature that pulls an outside identity
 * provider into the system, and a project that has not configured one must not get an endpoint that
 * accepts third-party tokens.
 */
export function isExternalIdentityEnabled(compilerOptions: types.compilerOptions): boolean {
    return isAuthEnabled(compilerOptions) && (compilerOptions.auth.externalIdentity?.enabled ?? false);
}

/**
 * Single gate for the account-deletion feature (API endpoint, service and the `/delete_account`
 * page). Enabled by default — `app.showSoftDeleted`-style opt-out, never opt-in.
 *
 * Auth is a hard requirement: a deletion endpoint with no way to authenticate could only ever
 * delete the wrong account, so an auth-less project gets the feature switched off regardless of
 * what `auth.deleteAccount` says.
 *
 * `?? true` rather than `|| true`: the latter swallows an explicit `false`.
 */
export function isAccountDeletionEnabled(compilerOptions: types.compilerOptions): boolean {
    return isAuthEnabled(compilerOptions) && (compilerOptions.auth.deleteAccount ?? true);
}

/**
 * Adapter-layer visibility policy for soft-deleted rows.
 *
 * Defaults to false, i.e. hide them. `true` turns the filter off app-wide — a deliberately blunt
 * lever, so every generation run says out loud that it is on. The value is baked into the generated
 * registry, which is what keeps it out of reach of any client.
 */
export function isShowSoftDeleted(compilerOptions: types.compilerOptions): boolean {
    const enabled = compilerOptions.app?.showSoftDeleted ?? false;

    if (enabled) {
        log.warn(
            `app.showSoftDeleted is ON — soft-deleted rows are visible to every query, are writable ` +
            `again through the ordinary CRUD path, and the account-state guard in ` +
            `Authentication.middleware will keep rejecting tombstones. ` +
            `Unset app.showSoftDeleted to restore the default (hidden).`
        );
    }

    return enabled;
}

/**
 * Single gate for every RBAC code path.
 *
 * RBAC is opt-in: it is enabled only when `useRBAC` is present AND declares at
 * least one role. An absent `useRBAC`, or an empty `roles` list, means "RBAC
 * off" — not "RBAC with zero roles".
 *
 * The distinction matters: an empty role list used to propagate into
 * `UserRole.role` as an empty JSON Schema enum, which
 * `json-schema-to-typescript` renders as the invalid type `role: ()` and which
 * aborted the whole generation. See docs/architecture/generatorPipeline.md.
 */
export function isRbacEnabled(compilerOptions: types.compilerOptions): boolean {
    const roles = compilerOptions.useRBAC?.roles;
    return Array.isArray(roles) && roles.length > 0;
}

export const defaultCompilerOptions: types.compilerOptions = {

    rootDir: ".",
    srcDir: "./src",
    sysDir: "./src/system",
    jsonSchemaDir: "./jsonSchema",
    openapiDir: "./openapi",
    generator: {
        commitBeforeGenerate: false,
    },
    app: {
        enableSwagger: true,
        useUserSchema: true,
        useStatefulRedisAuth: false,
        allowApiCreateUpdate_id: false,
        showSoftDeleted: false,
    },
    useRBAC: {
        roles: ["user"],
        default: "user",
    },
    auth: {
        localAuth: true,
        useHttpOnlyCookieToken: false,
        deleteAccount: true,
        // Opt-in, and the default is emitted so the knob is discoverable in a written vex.config.json.
        externalIdentity: {
            enabled: false,
        },
        oauthProviders: {
            google: false,
            microsoft: false,
            apple: false,
            github: false,
        },
    },
    _:{
        // headerComment: "",
        writtedDir: [],
    },
    dbType: "sql",
};

export default {
    defaultCompilerOptions,
    getDefaultHeaderComment,
    getStaticHeaderComment,
    getSimpleHeaderComment,
    getSimpleStaticHeaderComment,
    OAuthProviders,
    isAuthEnabled,
    isExternalIdentityEnabled,
    isRbacEnabled,
    isAccountDeletionEnabled,
    isShowSoftDeleted,
};