/**
 * Normalization applied to generated output before it is compared to (or stored
 * as) a golden file. Only changes that carry no signal are stripped — anything
 * that would hide a real generator regression must stay in the golden.
 */

/**
 * Header comments embed the generator version, e.g.
 * `Generated by veryExpress@0.7.9`. A version bump would otherwise rewrite
 * every golden file, so the version is pinned to a placeholder.
 */
const VERSION_PATTERN = /veryExpress@\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?/g;

export function normalizeContent(content: string, workDir: string): string {
    return content
        .replace(VERSION_PATTERN, "veryExpress@<version>")
        // absolute temp paths must never leak into a golden file
        .replaceAll(workDir, "<workdir>")
        .replaceAll(workDir.replace(/\\/g, "/"), "<workdir>")
        // a checkout on Windows must not fail every scenario
        .replace(/\r\n/g, "\n");
}
