import path from "path";

import utils from "../../utils";
import log from "../../utils/logger";
import * as types from "../../types/types";
import { processSchema, ZodSchemaDef } from "../controller/controllers.generator";

// ─── types ────────────────────────────────────────────────────────────────────

type DocumentEntry = {
    documentName: string;
    bodySchemaName: string;
    paramsSchemaName: string;
    bodySchema: ZodSchemaDef;
    paramsSchema: ZodSchemaDef;
};

// ─── helpers ───────────────────────────────────────────────────────────────────

/** Render a ZodSchemaDef subset for one location into a z.object({...}) source string */
function renderZodObjectSource(schemaDef: ZodSchemaDef, location: "body" | "params" | "query"): string {
    const fields = Object.keys(schemaDef)
        .filter(k => schemaDef[k].in === location && !k.includes("."))
        .map(k => `        ${JSON.stringify(k)}: ${schemaDef[k].chain}`)
        .join(",\n");

    if (!fields) return "z.object({})";
    return `z.object({\n${fields}\n    })`;
}

// ─── compile ──────────────────────────────────────────────────────────────────

export async function compile(options: {
    documents: { schema: types.jsonSchema, config: types.documentConfig }[];
    routeDir: string;
    compilerOptions: types.compilerOptions;
}): Promise<void> {
    log.process("OAS Registry");

    const entries: DocumentEntry[] = [];

    for (const doc of options.documents) {
        const schema = doc.schema;
        const schemaConfig = doc.config;
        // Build body ZodSchemaDef from all schema properties
        const bodySchema: ZodSchemaDef = {};
        if (schema.type === "object") {
            for (const key in schema.properties) {
                Object.assign(bodySchema, processSchema({
                    fieldName: key,
                    body: schema.properties[key],
                    required: schema.required?.includes(key) ?? false,
                }));
            }
        }

        // Build id path-param ZodSchemaDef
        const idXFormat = schema.properties["_id"]?.["x-format"];
        const idType = idXFormat === "PrimaryUUID" ? "string" : "integer";
        const paramsSchema = processSchema({
            fieldName: "id",
            required: true,
            param: {
                name: "id",
                in: "path",
                required: true,
                schema: { type: idType, ["x-format"]: idXFormat ?? undefined } as any,
            },
        });

        entries.push({
            documentName: schemaConfig.documentName,
            bodySchemaName: `${schemaConfig.documentName}BodySchema`,
            paramsSchemaName: `${schemaConfig.documentName}ParamsSchema`,
            bodySchema,
            paramsSchema,
        });
    }

    // ── render file source ────────────────────────────────────────────────────
    const lines: string[] = [
        `/**`,
        ` * Generated by VeryExpress`,
        ` * DO NOT EDIT — re-generated on every vex run`,
        ` */`,
        ``,
        `import { z } from "zod";`,
        `import { extendZodWithOpenApi, OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";`,
        ``,
        `extendZodWithOpenApi(z);`,
        ``,
        `export const oasRegistry = new OpenAPIRegistry();`,
        ``,
        `// ── BearerAuth security scheme ──────────────────────────────────────────`,
        `oasRegistry.registerComponent("securitySchemes", "BearerAuth", {`,
        `    type: "http",`,
        `    scheme: "bearer",`,
        `    bearerFormat: "JWT",`,
        `});`,
        ``,
    ];

    for (const doc of entries) {
        lines.push(`// ── ${doc.documentName} ──────────────────────────────────────────────────────`);

        // exported named schemas — controllers import these to call registerPath()
        const bodyHasFields = Object.keys(doc.bodySchema).length > 0;
        if (bodyHasFields) {
            lines.push(`export const ${doc.bodySchemaName} = oasRegistry.register(`);
            lines.push(`    "${doc.documentName}Body",`);
            lines.push(`    ${renderZodObjectSource(doc.bodySchema, "body")}`);
            lines.push(`);`);
        }
        else {
            lines.push(`export const ${doc.bodySchemaName} = z.object({});`);
        }

        lines.push(`export const ${doc.paramsSchemaName} = oasRegistry.register(`);
        lines.push(`    "${doc.documentName}Params",`);
        lines.push(`    ${renderZodObjectSource(doc.paramsSchema, "params")}`);
        lines.push(`);`);
        lines.push(``);
    }

    const source = lines.join("\n");
    const outPath = path.posix.join(options.routeDir, "OasRegistry.gen.ts");
    utils.common.writeFile("OAS Registry", outPath, source);
}
