import utils from "~/utils";
import log from "~/utils/logger";
import * as types from "~/types/types";

interface TsoaSpec {
    outputDirectory: string;
    specVersion: number;
    name: string;
    description: string;
    version: string;
    securityDefinitions?: Record<string, unknown>;
}

interface TsoaRoutes {
    routesDir: string;
    middleware: "express";
}

interface TsoaConfig {
    entryFile: string;
    noImplicitAdditionalProperties: "throw-on-extras" | "silently-ignore-extras" | "ignore";
    controllerPathGlobs: string[];
    spec: TsoaSpec;
    routes: TsoaRoutes;
}

export function compile(options: {
    outPath: string;
    controllerGlob: string;
    routesDir: string;
    specOutputDir: string;
    compilerOptions: types.compilerOptions;
}): void {
    log.process("TSOA : tsoa.json");

    const config: TsoaConfig = {
        entryFile: "src/server.ts",
        noImplicitAdditionalProperties: "throw-on-extras",
        controllerPathGlobs: [options.controllerGlob],
        spec: {
            outputDirectory: options.specOutputDir,
            specVersion: 3,
            name: "VeryExpress Generated API",
            description: "Auto-generated by VeryExpress",
            version: "1.0.0",
        },
        routes: {
            routesDir: options.routesDir,
            middleware: "express",
        },
    };

    if (utils.generator.isAuthEnabled(options.compilerOptions)) {
        config.spec.securityDefinitions = {
            BearerAuth: {
                type: "http",
                scheme: "bearer",
                bearerFormat: "JWT",
            },
            AuthIndex: {
                type: "apiKey",
                in: "header",
                name: "X-Auth-Index",
            },
        };
    }

    utils.common.writeFile("TSOA Config", options.outPath, JSON.stringify(config, null, 4));
}
